In [13]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import time
from sklearn import datasets
import pandas as pd
from scipy import stats
from sklearn.naive_bayes import GaussianNB

In [2]:
iris = datasets.load_iris()
DATA = np.c_[iris.data,iris.target]

In [6]:
def NBC(points,targets,train):
    probs = []
    separated = [[x for x, t in zip(train, targets) if t == c] for c in np.unique(targets)]
    for _ in np.unique(targets).astype(int):
        class_prob = 1
        for column in range(train.shape[1]):
            class_prob *= stats.norm.pdf(points[:,column],np.vstack(separated[_])[:,column].mean(),
                                         np.vstack(separated[_])[:,column].std())
        probs.append(class_prob)
    return np.argmax(probs, axis=0)
            

In [11]:
from sklearn.cross_validation import train_test_split
np.random.seed(42)
train, test = train_test_split(DATA, test_size = 0.2)
NBC(test[:,:-1],train[:,-1],train[:,:-1])==test[:,-1]#is it good enough

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True], dtype=bool)

In [16]:
%time
NBC(test[:,:-1],train[:,-1],train[:,:-1])

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 5.72 µs


array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2, 0,
       2, 2, 2, 2, 2, 0, 0])

# Compare with sklearn

In [14]:
gaNB = GaussianNB()

In [17]:
%time
gaNB.fit(train[:,:-1],train[:,-1])
gaNB.predict(test[:,:-1])

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 10.5 µs


array([ 1.,  0.,  2.,  1.,  1.,  0.,  1.,  2.,  1.,  1.,  2.,  0.,  0.,
        0.,  0.,  1.,  2.,  1.,  1.,  2.,  0.,  2.,  0.,  2.,  2.,  2.,
        2.,  2.,  0.,  0.])